### ISSUE TITLE
testsuite hanging on Linux

### ISSUE THREAD

**Issue by juhp** [daanx/isocline#5]
I tried to build 1.0.5 and run the testsuite on Fedora Linux 35 x86_64 (ghc-8.10.5 and LTS 18), but it seems to hang for me.
Then after interrupting it, test-example grabs a cpu... any ideas?
Is there any more information I can provide? (Same thing happened with 1.0.4.)

**Comment by juhp** [comment]
From my limited testing it seems I need to enter Return for the testsuite to complete.

**Comment by daanx** [comment]
I think this is fixed since v1.0.7.

**Comment by juhp** [comment]
I am afraid I can still reproduce with 1.0.9 on Fedora Linux.

Anyway not a big deal I will just disable the testsuite here for now.

**Comment by felixonmars** [comment]
Same here on Arch Linux with 1.0.9. I'll pipe `echo` to it to workaround for now:

```
echo | runhaskell Setup test
```
